In [42]:
import numpy as np

In [43]:
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7]])
d = np.zeros((2, 4))
e = np.random.rand(2, 5)

In [44]:
print a
print b
print c
print d
print e

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.08531352  0.93157364  0.62608296  0.28553793  0.03715542]
 [ 0.45801661  0.31150034  0.86618069  0.66648154  0.18572198]]


In [45]:
print a*0.1
print c*0.2
print a*b
print a*b*0.2
print a*c
#print a*e

[ 0.   0.1  0.2  0.3]
[[ 0.   0.2  0.4  0.6]
 [ 0.8  1.   1.2  1.4]]
[ 0  5 12 21]
[ 0.   1.   2.4  4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [46]:
a = np.zeros((1,4))
b = np.zeros((4,3))
c = a.dot(b)
print a
print b
print c
print c.shape

[[ 0.  0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]]
(1, 3)
